# Generated by Django 3.0.4 on 2020-06-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E', 'Elly Morrison'), ('A', 'Avik Amble'), ('B', 'Benson Adebayo')], default='', max_length=100)),
                ('education', models.IntegerField(choices=[(40, 'Master Degree'), (30, 'Bachelor Degree'), (20, 'High School Diploma'), (10, 'A Level')], default='')),
                ('experience', models.IntegerField(choices=[(60, 'Super experienced 11 years and above'), (50, 'Very experienced 9 to 10 years'), (40, 'Experienced 6 to 8 years'), (30, 'Moderate Experience 3 to 5 years'), (20, 'New 1 to 2 years'), (10, 'No Experience 0 to 1 year')], default='')),
                ('location', models.IntegerField(choices=[(70, '5 to 10 miles away'), (60, '11 to 20 miles away'), (50, '21 to 30 miles away'), (40, '31 to 40 miles away'), (30, '41 to 50 miles away'), (20, '51 to  and above miles away')], default='')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('employment_status', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Freelance', 'Freelancer')], max_length=10)),
                ('vacancy', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(choices=[('Retail', 'Retail'), ('Banking', 'Banking'), ('Security', 'Security'), ('Transportation', 'Transportation'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('IT', 'IT')], max_length=30)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=120)),
                ('Salary', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('application_deadline', models.DateTimeField()),
                ('published_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
