# Generated by Django 3.0.3 on 2020-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_applyjob_about_you'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='name',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='availability',
            field=models.CharField(blank=True, choices=[('I', 'Available Immediately - 2 to 4 weeks'), ('N', 'Normal Availability - 1 to 3 Months'), ('U', 'Unsure - Undecided')], max_length=40),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='entry_status',
            field=models.CharField(blank=True, choices=[('NEW', 'Entry Level'), ('EX', 'Experienced')], max_length=20),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
