# Generated by Django 3.0.4 on 2020-03-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
