# Generated by Django 3.0.4 on 2020-03-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_delete_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='entry_status',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='education',
            field=models.CharField(blank=True, choices=[('GRA', 'Graduate'), ('PG', 'Postgraduate')], max_length=20),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='experience',
            field=models.CharField(blank=True, choices=[('N', 'New - 0 to 2 years'), ('M', 'Moderate - 3 to 5 years'), ('E', 'Experienced - 5 years and above')], max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
