# Generated by Django 3.0.4 on 2020-03-15 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20200315_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.JobListing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.ApplyJob')),
            ],
        ),
    ]
