# Generated by Django 3.0.4 on 2020-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='location',
            field=models.CharField(default='', max_length=70),
        ),
    ]
