# Generated by Django 3.0.4 on 2020-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20200317_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='education',
            field=models.IntegerField(choices=[(1, 'PhD'), (2, 'Master Degree'), (3, 'Bachelor Degree'), (4, 'Undergraduate')], default=''),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Super experienced 11 years and above'), (2, 'Very experienced 9 to 10 years'), (3, 'Experienced 6 to 8 years'), (4, 'Moderate Experience 3 to 5 years'), (5, 'New 1 to 2 years'), (6, 'No Experience 0 to 1 year')], default=''),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='location',
            field=models.IntegerField(choices=[(1, '5 to 99 miles away'), (2, '100 to 299 miles away'), (3, '300 to 399 miles away'), (4, '400 to 499 miles away'), (5, '500 to 599 miles away'), (6, '600 to 999 miles away'), (7, '1000 and above miles away')], default=''),
        ),
    ]
