# Generated by Django 3.0.4 on 2020-05-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_applicant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='web',
        ),
    ]
