# Generated by Django 3.0.4 on 2020-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20200504_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='first_name',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='last_name',
            field=models.CharField(choices=[('E', 'Elly Morrison'), ('A', 'Anika Agate'), ('V', 'Victoria Adebayo')], default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
