# Generated by Django 3.0.4 on 2020-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20200504_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
