# Generated by Django 3.0.4 on 2020-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_contact_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Banking', 'Banking'), ('Security', 'Security'), ('Transportation', 'Transportation'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('IT', 'IT')], max_length=30),
        ),
    ]
