# Generated by Django 3.0.4 on 2020-06-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20200601_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')], default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_2',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')], default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_3',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')], default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_4',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')], default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_5',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')], default=''),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
