# Generated by Django 3.0.4 on 2020-06-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_auto_20200601_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(choices=[(1, 'strongly agree'), (2, 'somewhat agree'), (3, 'neither nor disagree'), (4, 'somewhat disagree'), (5, 'strongly disagree')]),
        ),
    ]
