# Generated by Django 3.0.4 on 2020-06-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_auto_20200601_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey_a',
            new_name='survey_1',
        ),
    ]
