# Generated by Django 3.0.4 on 2020-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_auto_20200601_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.CharField(choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_2',
            field=models.CharField(choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3',
            field=models.CharField(choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_4',
            field=models.CharField(choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_5',
            field=models.CharField(choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], default='', max_length=100),
        ),
    ]
