# Generated by Django 3.0.4 on 2020-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_auto_20200601_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.CharField(blank=True, choices=[('STA', 'strongly agree'), ('SMA', 'somewhat agree'), ('NNA', 'neither agree nor disagree'), ('SMD', 'somewhat disagree'), ('STD', 'strongly disagree')], max_length=100),
        ),
    ]
