# Generated by Django 3.0.4 on 2020-06-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20200601_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_2',
            new_name='five',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_3',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_1',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey_1',
            new_name='surveya',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_4',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_5',
            new_name='two',
        ),
    ]
