# Generated by Django 3.0.4 on 2020-06-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_auto_20200601_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
