# Generated by Django 3.0.4 on 2020-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_action_date', models.DateTimeField(auto_now_add=True)),
                ('log_instance_id', models.BigIntegerField()),
                ('log_action_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_instance_id', models.BigIntegerField(default=-1)),
                ('log_comment', models.CharField(max_length=2000)),
                ('log_radio1', models.CharField(default='', max_length=2000)),
                ('log_about', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LogInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_instance_creation_date', models.DateTimeField(auto_now_add=True)),
                ('log_identification_string', models.CharField(default='not provided', max_length=200)),
            ],
        ),
    ]
