# Generated by Django 3.0.4 on 2020-07-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAction',
        ),
        migrations.DeleteModel(
            name='LogComment',
        ),
        migrations.DeleteModel(
            name='LogInstance',
        ),
    ]
