# Generated by Django 3.0.4 on 2020-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
